name: Dedupe and Sort Domains
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: write
jobs:
  dedupe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Check for duplicates and sort alphabetically
        run: grep -v '^$' emails.txt | sort -uo emails.txt
      - name: Commit Changes
        run: |
          git add emails.txt
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ ! -z "$(git status --porcelain)" ]; then
          git commit -m "[chore]: Sort and dedupe \`emails.txt\`"
          git push
          fi
